import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type LangCode = "ar" | "es" | "pt" | "ru" | "fr" | "it";

const LANGUAGES: { code: LangCode; name: string; nativeName: string; flag: string; sortOrder: number }[] = [
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦", sortOrder: 10 },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸", sortOrder: 20 },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇵🇹", sortOrder: 30 },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺", sortOrder: 40 },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷", sortOrder: 50 },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹", sortOrder: 60 },
];

const T: Record<string, Record<LangCode, string>> = {
  "header.nav.home": { ar: "الرئيسية", es: "Inicio", pt: "Início", ru: "Главная", fr: "Accueil", it: "Home" },
  "header.nav.products": { ar: "المنتجات", es: "Productos", pt: "Produtos", ru: "Продукция", fr: "Produits", it: "Prodotti" },
  "header.nav.custom": { ar: "خدمة التخصيص", es: "Servicio Personalizado", pt: "Serviço Personalizado", ru: "Индивидуальные услуги", fr: "Service Personnalisé", it: "Servizio Personalizzato" },
  "header.nav.news": { ar: "الأخبار", es: "Noticias", pt: "Notícias", ru: "Новости", fr: "Actualités", it: "Notizie" },
  "header.nav.faq": { ar: "الأسئلة الشائعة", es: "Preguntas Frecuentes", pt: "Perguntas Frequentes", ru: "Часто задаваемые вопросы", fr: "FAQ", it: "FAQ" },
  "header.nav.about": { ar: "من نحن", es: "Sobre Nosotros", pt: "Sobre Nós", ru: "О компании", fr: "À Propos", it: "Chi Siamo" },
  "header.nav.contact": { ar: "اتصل بنا", es: "Contacto", pt: "Contato", ru: "Контакты", fr: "Contact", it: "Contatti" },
  "header.inquiryNow": { ar: "استفسر الآن", es: "Consultar Ahora", pt: "Consultar Agora", ru: "Отправить запрос", fr: "Demander un Devis", it: "Richiedi Ora" },
  "header.search": { ar: "بحث", es: "Buscar", pt: "Buscar", ru: "Поиск", fr: "Rechercher", it: "Cerca" },
  "header.searchPlaceholder": { ar: "ابحث عن المنتجات والأخبار...", es: "Buscar productos, noticias...", pt: "Buscar produtos, notícias...", ru: "Поиск товаров, новостей...", fr: "Rechercher produits, actualités...", it: "Cerca prodotti, notizie..." },
  "header.searchTypeProduct": { ar: "منتج", es: "Producto", pt: "Produto", ru: "Товар", fr: "Produit", it: "Prodotto" },
  "header.searchTypeNews": { ar: "خبر", es: "Noticia", pt: "Notícia", ru: "Новость", fr: "Actualité", it: "Notizia" },
  "header.searchNoResults": { ar: "لا توجد نتائج لـ", es: "Sin resultados para", pt: "Nenhum resultado para", ru: "Ничего не найдено по запросу", fr: "Aucun résultat pour", it: "Nessun risultato per" },
  "header.searchHint": { ar: "اكتب للبحث عن المنتجات والأخبار", es: "Escribe para buscar productos y noticias", pt: "Digite para buscar produtos e notícias", ru: "Введите запрос для поиска товаров и новостей", fr: "Tapez pour rechercher produits et actualités", it: "Digita per cercare prodotti e notizie" },
  "header.language": { ar: "اللغة", es: "Idioma", pt: "Idioma", ru: "Язык", fr: "Langue", it: "Lingua" },
  "header.wishlist": { ar: "المفضلة", es: "Lista de Deseos", pt: "Lista de Desejos", ru: "Избранное", fr: "Liste de Souhaits", it: "Lista dei Desideri" },
  "header.cart": { ar: "السلة", es: "Carrito", pt: "Carrinho", ru: "Корзина", fr: "Panier", it: "Carrello" },

  "footer.contactUs": { ar: "اتصل بنا", es: "Contáctenos", pt: "Contate-nos", ru: "Свяжитесь с нами", fr: "Contactez-nous", it: "Contattaci" },
  "footer.companyName": { ar: "كيليكولي لألعاب وحرف الراتنج", es: "Kelikuli Juguetes y Manualidades de Resina", pt: "Kelikuli Brinquedos e Artesanato em Resina", ru: "Kelikuli — игрушки и изделия из смолы", fr: "Kelikuli Jouets et Objets Artisanaux en Résine", it: "Kelikuli Giocattoli e Manufatti in Resina" },
  "footer.whatsapp": { ar: "واتساب", es: "WhatsApp", pt: "WhatsApp", ru: "WhatsApp", fr: "WhatsApp", it: "WhatsApp" },
  "footer.wechat": { ar: "وي تشات", es: "WeChat", pt: "WeChat", ru: "WeChat", fr: "WeChat", it: "WeChat" },
  "footer.aboutUs": { ar: "من نحن", es: "Sobre Nosotros", pt: "Sobre Nós", ru: "О компании", fr: "À Propos", it: "Chi Siamo" },
  "footer.about.profile": { ar: "نبذة عن الشركة", es: "Perfil de la Empresa", pt: "Perfil da Empresa", ru: "О компании", fr: "Profil de l'Entreprise", it: "Profilo Aziendale" },
  "footer.about.factory": { ar: "مزايا المصنع", es: "Ventajas de la Fábrica", pt: "Vantagens da Fábrica", ru: "Преимущества завода", fr: "Atouts de l'Usine", it: "Vantaggi dello Stabilimento" },
  "footer.about.oem": { ar: "خدمة التصنيع OEM/ODM", es: "Servicio OEM/ODM", pt: "Serviço OEM/ODM", ru: "Услуги OEM/ODM", fr: "Service OEM/ODM", it: "Servizio OEM/ODM" },
  "footer.about.contact": { ar: "اتصل بنا", es: "Contáctenos", pt: "Contate-nos", ru: "Свяжитесь с нами", fr: "Contactez-nous", it: "Contattaci" },
  "footer.product": { ar: "منتج", es: "Producto", pt: "Produto", ru: "Товар", fr: "Produit", it: "Prodotto" },
  "footer.products.custom": { ar: "ألعاب راتنج مخصصة", es: "Juguetes de Resina Personalizados", pt: "Brinquedos de Resina Personalizados", ru: "Изделия из смолы на заказ", fr: "Jouets en Résine Personnalisés", it: "Giocattoli in Resina Personalizzati" },
  "footer.products.blindBox": { ar: "ألعاب الصندوق العشوائي", es: "Juguetes Blind Box", pt: "Brinquedos Blind Box", ru: "Игрушки Blind Box", fr: "Jouets Blind Box", it: "Giocattoli Blind Box" },
  "footer.products.figurines": { ar: "تماثيل الراتنج", es: "Figuras de Resina", pt: "Figuras de Resina", ru: "Фигурки из смолы", fr: "Figurines en Résine", it: "Statuine in Resina" },
  "footer.products.festival": { ar: "زينة المناسبات", es: "Decoraciones Festivas", pt: "Decorações Festivas", ru: "Праздничный декор", fr: "Décorations de Fêtes", it: "Decorazioni Festive" },
  "footer.products.luckyCat": { ar: "سلسلة القطة المحظوظة", es: "Serie Gato de la Suerte", pt: "Série Gato da Sorte", ru: "Серия «Кот удачи»", fr: "Série Chat Porte-Bonheur", it: "Serie Gatto Fortunato" },
  "footer.products.garden": { ar: "سلسلة الحديقة", es: "Serie de Jardín", pt: "Série de Jardim", ru: "Серия «Сад»", fr: "Série Jardin", it: "Serie Giardino" },
  "footer.news": { ar: "الأخبار", es: "Noticias", pt: "Notícias", ru: "Новости", fr: "Actualités", it: "Notizie" },
  "footer.news.company": { ar: "أخبار الشركة", es: "Noticias de la Empresa", pt: "Notícias da Empresa", ru: "Новости компании", fr: "Actualités de l'Entreprise", it: "Notizie Aziendali" },
  "footer.news.updates": { ar: "تحديثات المنتجات", es: "Actualizaciones de Productos", pt: "Atualizações de Produtos", ru: "Обновления продукции", fr: "Mises à Jour Produits", it: "Aggiornamenti Prodotti" },
  "footer.news.guide": { ar: "دليل ألعاب الراتنج المخصصة", es: "Guía de Juguetes de Resina Personalizados", pt: "Guia de Brinquedos de Resina Personalizados", ru: "Руководство по изделиям из смолы на заказ", fr: "Guide des Jouets en Résine Personnalisés", it: "Guida ai Giocattoli in Resina Personalizzati" },
  "footer.news.industry": { ar: "أخبار الصناعة", es: "Noticias de la Industria", pt: "Notícias do Setor", ru: "Отраслевые новости", fr: "Actualités du Secteur", it: "Notizie del Settore" },
  "footer.scanQr": { ar: "امسح رمز الاستجابة السريعة", es: "Escanea el Código QR", pt: "Escaneie o Código QR", ru: "Сканируйте QR-код", fr: "Scannez le Code QR", it: "Scansiona il Codice QR" },
  "footer.scanToContact": { ar: "امسح للتواصل معنا عبر وي تشات", es: "Escanea para contactarnos por WeChat", pt: "Escaneie para nos contatar pelo WeChat", ru: "Отсканируйте, чтобы связаться с нами в WeChat", fr: "Scannez pour nous contacter sur WeChat", it: "Scansiona per contattarci su WeChat" },
  "footer.copyright": { ar: "كيليكولي لألعاب وحرف الراتنج. جميع الحقوق محفوظة.", es: "Kelikuli Juguetes y Manualidades de Resina. Todos los derechos reservados.", pt: "Kelikuli Brinquedos e Artesanato em Resina. Todos os direitos reservados.", ru: "Kelikuli — игрушки и изделия из смолы. Все права защищены.", fr: "Kelikuli Jouets et Objets Artisanaux en Résine. Tous droits réservés.", it: "Kelikuli Giocattoli e Manufatti in Resina. Tutti i diritti riservati." },

  "floatingContact.chatNow": { ar: "تحدث الآن", es: "Chatear Ahora", pt: "Conversar Agora", ru: "Написать сейчас", fr: "Discuter Maintenant", it: "Chatta Ora" },
  "floatingContact.wechatTitle": { ar: "وي تشات", es: "WeChat", pt: "WeChat", ru: "WeChat", fr: "WeChat", it: "WeChat" },
  "floatingContact.wechatSubtitle": { ar: "امسح لإضافتنا على وي تشات", es: "Escanea para agregarnos en WeChat", pt: "Escaneie para nos adicionar no WeChat", ru: "Отсканируйте, чтобы добавить нас в WeChat", fr: "Scannez pour nous ajouter sur WeChat", it: "Scansiona per aggiungerci su WeChat" },
  "floatingContact.close": { ar: "إغلاق", es: "Cerrar", pt: "Fechar", ru: "Закрыть", fr: "Fermer", it: "Chiudi" },

  "breadcrumb.home": { ar: "الرئيسية", es: "Inicio", pt: "Início", ru: "Главная", fr: "Accueil", it: "Home" },

  "home.hero.main.titleLine1": { ar: "تمثال الراتنج", es: "Figura de Resina", pt: "Figura de Resina", ru: "Фигурка из смолы", fr: "Figurine en Résine", it: "Statuina in Resina" },
  "home.hero.main.titleLine2": { ar: "الشركة المصنعة", es: "Fabricante", pt: "Fabricante", ru: "Производитель", fr: "Fabricant", it: "Produttore" },
  "home.hero.main.subtitle": { ar: "مصنع ألعاب راتنج مخصصة | مُصنّع صناديق عشوائية | تماثيل راتنج بالجملة", es: "Fábrica de Juguetes de Resina Personalizados | Fabricante de Blind Box | Figuras de Resina al por Mayor", pt: "Fábrica de Brinquedos de Resina Personalizados | Fabricante de Blind Box | Figuras de Resina no Atacado", ru: "Завод по производству изделий из смолы на заказ | Производитель Blind Box | Оптовые фигурки из смолы", fr: "Usine de Jouets en Résine Personnalisés | Fabricant de Blind Box | Figurines en Résine en Gros", it: "Fabbrica di Giocattoli in Resina Personalizzati | Produttore di Blind Box | Statuine in Resina all'Ingrosso" },
  "home.hero.main.badge": { ar: "تخصيص الصناديق العشوائية", es: "Personalización de Blind Box", pt: "Personalização de Blind Box", ru: "Индивидуальные Blind Box", fr: "Personnalisation Blind Box", it: "Personalizzazione Blind Box" },
  "home.hero.main.tagline": { ar: "رؤيتك، تميز فاخر.", es: "Tu Visión, Excelencia Premium.", pt: "Sua Visão, Excelência Premium.", ru: "Ваше видение — наше премиальное мастерство.", fr: "Votre Vision, Excellence Premium.", it: "La Tua Visione, Eccellenza Premium." },
  "home.hero.main.check1": { ar: "طلبات OEM/ODM مخصصة", es: "Pedidos Personalizados OEM/ODM", pt: "Pedidos Personalizados OEM/ODM", ru: "Индивидуальные заказы OEM/ODM", fr: "Commandes Personnalisées OEM/ODM", it: "Ordini Personalizzati OEM/ODM" },
  "home.hero.main.check2": { ar: "جودة مرسومة يدويًا", es: "Calidad Pintada a Mano", pt: "Qualidade Pintada à Mão", ru: "Качественная ручная роспись", fr: "Qualité Peinte à la Main", it: "Qualità Dipinta a Mano" },
  "home.hero.main.check3": { ar: "يقبل الحد الأدنى المنخفض للطلب", es: "MOQ Bajo Aceptado", pt: "MOQ Baixo Aceito", ru: "Приём заказов с низким MOQ", fr: "MOQ Faible Accepté", it: "MOQ Basso Accettato" },
  "home.hero.main.check4": { ar: "صديق للبيئة", es: "Ecológico", pt: "Ecológico", ru: "Экологичность", fr: "Écologique", it: "Ecologico" },
  "home.hero.getQuote": { ar: "احصل على عرض سعر", es: "Solicitar Cotización", pt: "Solicitar Orçamento", ru: "Получить предложение", fr: "Obtenir un Devis", it: "Richiedi un Preventivo" },
  "home.hero.getQuoteLower": { ar: "احصل على عرض سعر", es: "Solicitar cotización", pt: "Solicitar orçamento", ru: "Получить предложение", fr: "Obtenir un devis", it: "Richiedi un preventivo" },
  "home.hero.lamp.titleLine1": { ar: "ديكور الراتنج", es: "Decoración de Resina", pt: "Decoração de Resina", ru: "Декор из смолы", fr: "Décoration en Résine", it: "Decorazione in Resina" },
  "home.hero.lamp.titleLine2": { ar: "إضاءة", es: "Luz", pt: "Luz", ru: "Светильник", fr: "Lumière", it: "Luce" },
  "home.hero.lamp.subtitle": { ar: "ديكور راتنج مصنوع يدويًا لأجواء دافئة ومريحة", es: "Decoración de Resina Artesanal para Espacios Cálidos y Acogedores", pt: "Decoração de Resina Artesanal para Espaços Aconchegantes", ru: "Ручной декор из смолы для тёплого и уютного пространства", fr: "Décoration en Résine Artisanale pour des Espaces Chaleureux", it: "Decorazione in Resina Artigianale per Spazi Caldi e Accoglienti" },
  "home.hero.lamp.feature1": { ar: "راتنج مصنوع يدويًا", es: "Resina Artesanal", pt: "Resina Artesanal", ru: "Ручная работа из смолы", fr: "Résine Artisanale", it: "Resina Artigianale" },
  "home.hero.lamp.feature2": { ar: "إضاءة محيطة دافئة", es: "Luz Ambiental Cálida", pt: "Luz Ambiente Quente", ru: "Тёплое рассеянное освещение", fr: "Lumière d'Ambiance Chaleureuse", it: "Luce Ambientale Calda" },
  "home.hero.lamp.feature3": { ar: "أفكار هدايا مميزة", es: "Ideas de Regalos Únicos", pt: "Ideias de Presentes Únicos", ru: "Уникальные идеи подарков", fr: "Idées Cadeaux Uniques", it: "Idee Regalo Uniche" },
  "home.hero.feature.oem": { ar: "تخصيص\nOEM/ODM", es: "Personalización\nOEM/ODM", pt: "Personalização\nOEM/ODM", ru: "Индивидуализация\nOEM/ODM", fr: "Personnalisation\nOEM/ODM", it: "Personalizzazione\nOEM/ODM" },
  "home.hero.feature.design": { ar: "تصميم\nمخصص", es: "Diseño\nPersonalizado", pt: "Design\nPersonalizado", ru: "Индивидуальный\nдизайн", fr: "Design\nPersonnalisé", it: "Design\nPersonalizzato" },
  "home.hero.feature.moq": { ar: "تصنيع\nبحد أدنى منخفض", es: "Fabricación\nMOQ Bajo", pt: "Fabricação\nMOQ Baixo", ru: "Производство\nс низким MOQ", fr: "Fabrication\nMOQ Faible", it: "Produzione\nMOQ Basso" },
  "home.hero.feature.global": { ar: "معايير\nعالمية", es: "Estándares\nGlobales", pt: "Padrões\nGlobais", ru: "Мировые\nстандарты", fr: "Normes\nInternationales", it: "Standard\nInternazionali" },
  "home.hero.feature.qc": { ar: "عمليات\nمراقبة جودة صارمة", es: "Procesos de\nControl de Calidad Estricto", pt: "Processos de\nControle de Qualidade Rigoroso", ru: "Строгий\nконтроль качества", fr: "Processus de\nContrôle Qualité Strict", it: "Processi di\nControllo Qualità Rigoroso" },

  "home.featured.heading": { ar: "مجموعات ألعاب الراتنج المميزة", es: "Colecciones Destacadas de Juguetes de Resina", pt: "Coleções em Destaque de Brinquedos de Resina", ru: "Популярные коллекции изделий из смолы", fr: "Collections Vedettes de Jouets en Résine", it: "Collezioni in Evidenza di Giocattoli in Resina" },
  "home.featured.viewAll": { ar: "عرض جميع المنتجات", es: "Ver Todos los Productos", pt: "Ver Todos os Produtos", ru: "Смотреть все товары", fr: "Voir Tous les Produits", it: "Vedi Tutti i Prodotti" },
  "home.featured.loading": { ar: "جارٍ تحميل المنتجات...", es: "Cargando productos...", pt: "Carregando produtos...", ru: "Загрузка товаров...", fr: "Chargement des produits...", it: "Caricamento prodotti..." },
  "home.featured.badge1.title": { ar: "مراقبة جودة صارمة", es: "Control de Calidad Estricto", pt: "Controle de Qualidade Rigoroso", ru: "Строгий контроль качества", fr: "Contrôle Qualité Strict", it: "Controllo Qualità Rigoroso" },
  "home.featured.badge1.sub": { ar: "من المواد الخام إلى المنتجات النهائية", es: "Desde materias primas hasta productos terminados", pt: "Da matéria-prima ao produto final", ru: "От сырья до готовой продукции", fr: "Des matières premières aux produits finis", it: "Dalle materie prime ai prodotti finiti" },
  "home.featured.badge2.title": { ar: "دعم OEM/ODM", es: "Soporte OEM/ODM", pt: "Suporte OEM/ODM", ru: "Поддержка OEM/ODM", fr: "Support OEM/ODM", it: "Supporto OEM/ODM" },
  "home.featured.badge2.sub": { ar: "حد أدنى منخفض للطلب وحلول مرنة", es: "MOQ bajo y soluciones flexibles", pt: "MOQ baixo e soluções flexíveis", ru: "Низкий MOQ и гибкие решения", fr: "MOQ faible et solutions flexibles", it: "MOQ basso e soluzioni flessibili" },
  "home.featured.badge3.title": { ar: "التسليم في الوقت المحدد", es: "Entrega Puntual", pt: "Entrega Pontual", ru: "Своевременная доставка", fr: "Livraison Ponctuelle", it: "Consegna Puntuale" },
  "home.featured.badge3.sub": { ar: "مدة تنفيذ سريعة وشحن موثوق", es: "Tiempo de entrega rápido y envío confiable", pt: "Prazo de entrega rápido e envio confiável", ru: "Короткие сроки и надёжная доставка", fr: "Délai rapide et expédition fiable", it: "Tempi rapidi e spedizione affidabile" },
  "home.featured.badge4.title": { ar: "الشحن حول العالم", es: "Envío Mundial", pt: "Envio Mundial", ru: "Доставка по всему миру", fr: "Livraison Mondiale", it: "Spedizione Mondiale" },
  "home.featured.badge4.sub": { ar: "التصدير إلى أكثر من 30 دولة", es: "Exportación a más de 30 países", pt: "Exportação para mais de 30 países", ru: "Экспорт в более чем 30 стран", fr: "Exportation vers plus de 30 pays", it: "Esportazione in oltre 30 paesi" },

  "home.categories.eyebrow": { ar: "منتجاتنا", es: "Nuestros Productos", pt: "Nossos Produtos", ru: "Наша продукция", fr: "Nos Produits", it: "I Nostri Prodotti" },
  "home.categories.heading": { ar: "فئات حرف الراتنج", es: "Categorías de Artesanía en Resina", pt: "Categorias de Artesanato em Resina", ru: "Категории изделий из смолы", fr: "Catégories d'Objets Artisanaux en Résine", it: "Categorie di Manufatti in Resina" },
  "home.categories.intro": { ar: "من التماثيل القابلة للتحصيل إلى الصناديق العشوائية ذات العلامات التجارية — نصنع مجموعة واسعة من منتجات الراتنج المرسومة يدويًا للمشترين حول العالم.", es: "Desde figuras coleccionables hasta blind boxes de marca — fabricamos una amplia gama de productos de resina pintados a mano para compradores de todo el mundo.", pt: "De figuras colecionáveis a blind boxes de marca — fabricamos uma ampla gama de produtos de resina pintados à mão para compradores em todo o mundo.", ru: "От коллекционных фигурок до брендированных Blind Box — мы производим широкий ассортимент изделий из смолы ручной росписи для покупателей по всему миру.", fr: "Des figurines de collection aux blind boxes de marque — nous fabriquons une large gamme de produits en résine peints à la main pour des acheteurs du monde entier.", it: "Dalle statuine da collezione alle blind box a marchio — produciamo un'ampia gamma di prodotti in resina dipinti a mano per acquirenti di tutto il mondo." },
  "home.categories.learnMore": { ar: "اعرف المزيد", es: "Saber más", pt: "Saiba mais", ru: "Узнать больше", fr: "En savoir plus", it: "Scopri di più" },
  "home.categories.figurines.title": { ar: "تماثيل الراتنج", es: "Figuras de Resina", pt: "Figuras de Resina", ru: "Фигурки из смолы", fr: "Figurines en Résine", it: "Statuine in Resina" },
  "home.categories.figurines.description": { ar: "تماثيل راتنج غير لامعة مرسومة يدويًا للتحصيل والبيع بالتجزئة وهدايا العلامات التجارية. يتوفر تطوير شخصيات مخصصة.", es: "Figuras de resina mate pintadas a mano para coleccionismo, venta minorista y regalos de marca. Desarrollo de personajes personalizados disponible.", pt: "Figuras de resina fosca pintadas à mão para colecionáveis, varejo e brindes de marca. Desenvolvimento de personagens personalizados disponível.", ru: "Матовые фигурки из смолы ручной росписи для коллекционирования, розничной продажи и брендированных подарков. Доступна разработка персонажей на заказ.", fr: "Figurines en résine mate peintes à la main pour la collection, la vente au détail et les cadeaux de marque. Développement de personnages personnalisés disponible.", it: "Statuine in resina opaca dipinte a mano per collezionismo, vendita al dettaglio e regali aziendali. Disponibile lo sviluppo di personaggi personalizzati." },
  "home.categories.blindBox.title": { ar: "مقتنيات الصناديق العشوائية", es: "Coleccionables Blind Box", pt: "Colecionáveis Blind Box", ru: "Коллекционные Blind Box", fr: "Objets de Collection Blind Box", it: "Collezionabili Blind Box" },
  "home.categories.blindBox.description": { ar: "سلاسل صناديق عشوائية غامضة مع إخراج فني كامل وتغليف وتطوير شخصيات لحقوق الملكية الفكرية للعلامات التجارية وتجار التجزئة.", es: "Series de blind box misteriosas con dirección artística completa, empaque y desarrollo de propiedad intelectual de personajes para marcas y minoristas.", pt: "Séries de blind box misteriosas com direção de arte completa, embalagem e desenvolvimento de propriedade intelectual de personagens para marcas e varejistas.", ru: "Серии загадочных Blind Box с полным художественным оформлением, упаковкой и разработкой авторских персонажей для брендов и ритейлеров.", fr: "Séries de blind box mystères avec direction artistique complète, emballage et développement de propriété intellectuelle de personnages pour marques et détaillants.", it: "Serie di blind box a sorpresa con direzione artistica completa, packaging e sviluppo di IP dei personaggi per brand e rivenditori." },
  "home.categories.zakka.title": { ar: "زينة راتنج زاكا", es: "Adornos de Resina Zakka", pt: "Enfeites de Resina Zakka", ru: "Декор из смолы в стиле Zakka", fr: "Objets Décoratifs en Résine Zakka", it: "Ornamenti in Resina Zakka" },
  "home.categories.zakka.description": { ar: "ديكور منزلي ساحر بأسلوب زاكا من الراتنج — تماثيل مصغرة وحيوانات وقطع نمط حياة للجملة والتجزئة.", es: "Encantadora decoración de resina estilo Zakka para el hogar — figuras en miniatura, animales y piezas de estilo de vida para venta al por mayor y minorista.", pt: "Encantadora decoração de resina estilo Zakka para o lar — figuras em miniatura, animais e peças de estilo de vida para atacado e varejo.", ru: "Очаровательный домашний декор из смолы в стиле Zakka — миниатюрные фигурки, животные и предметы для дома, для опта и розницы.", fr: "Charmante décoration d'intérieur en résine de style Zakka — figurines miniatures, animaux et objets lifestyle pour la vente en gros et au détail.", it: "Affascinante decorazione per la casa in resina in stile Zakka — statuine in miniatura, animali e pezzi lifestyle per ingrosso e dettaglio." },
  "home.categories.seasonal.title": { ar: "حرف راتنج موسمية", es: "Artesanías de Resina de Temporada", pt: "Artesanato de Resina Sazonal", ru: "Сезонные изделия из смолы", fr: "Objets Artisanaux en Résine Saisonniers", it: "Manufatti in Resina Stagionali" },
  "home.categories.seasonal.description": { ar: "هدايا راتنج بمناسبة عيد الميلاد وهالوين وعيد الفصح والمناسبات. مجموعات موسمية جاهزة للجملة ويتم تحديثها سنويًا.", es: "Regalos de resina con temática de Navidad, Halloween, Pascua y festividades. Colecciones estacionales listas para mayoreo, actualizadas anualmente.", pt: "Presentes de resina com temas de Natal, Halloween, Páscoa e feriados. Coleções sazonais prontas para atacado, atualizadas anualmente.", ru: "Праздничные подарки из смолы на тему Рождества, Хэллоуина, Пасхи и других праздников. Готовые к оптовой продаже сезонные коллекции обновляются ежегодно.", fr: "Cadeaux en résine sur le thème de Noël, Halloween, Pâques et autres fêtes. Collections saisonnières prêtes à la vente en gros, mises à jour chaque année.", it: "Regali in resina a tema Natale, Halloween, Pasqua e altre festività. Collezioni stagionali pronte per l'ingrosso, aggiornate ogni anno." },
  "home.categories.customToys.title": { ar: "ألعاب راتنج مخصصة", es: "Juguetes de Resina Personalizados", pt: "Brinquedos de Resina Personalizados", ru: "Изделия из смолы на заказ", fr: "Jouets en Résine Personnalisés", it: "Giocattoli in Resina Personalizzati" },
  "home.categories.customToys.description": { ar: "تطوير ألعاب راتنج مخصصة بالكامل من الرسم إلى الإنتاج الضخم. OEM/ODM للعلامات التجارية والملكية الفكرية والحملات الترويجية.", es: "Desarrollo de juguetes de resina totalmente personalizados desde el boceto hasta la producción en masa. OEM/ODM para marcas, IPs y campañas promocionales.", pt: "Desenvolvimento de brinquedos de resina totalmente personalizados, do esboço à produção em massa. OEM/ODM para marcas, IPs e campanhas promocionais.", ru: "Полностью индивидуальная разработка игрушек из смолы — от эскиза до массового производства. OEM/ODM для брендов, IP и промо-кампаний.", fr: "Développement de jouets en résine entièrement personnalisés, du croquis à la production de masse. OEM/ODM pour marques, licences et campagnes promotionnelles.", it: "Sviluppo di giocattoli in resina completamente personalizzati, dallo schizzo alla produzione di massa. OEM/ODM per brand, IP e campagne promozionali." },
  "home.categories.snowGlobes.title": { ar: "كرات الثلج والمزيد", es: "Bolas de Nieve y Más", pt: "Globos de Neve e Mais", ru: "Снежные шары и другое", fr: "Boules à Neige et Plus", it: "Palle di Neve e Altro" },
  "home.categories.snowGlobes.description": { ar: "كرات ثلج من الراتنج ومغناطيس ثلاجة وحصالات نقود. مثالية للهدايا التذكارية والهدايا الترويجية وبيع متاجر الهدايا بالجملة.", es: "Bolas de nieve de resina, imanes de nevera y alcancías. Ideales para souvenirs, regalos promocionales y venta al por mayor en tiendas de regalos.", pt: "Globos de neve de resina, ímãs de geladeira e cofrinhos. Ideais para souvenires, brindes promocionais e atacado para lojas de presentes.", ru: "Снежные шары, магниты на холодильник и копилки из смолы. Отлично подходят для сувениров, промо-подарков и оптовой продажи в сувенирных магазинах.", fr: "Boules à neige, magnets et tirelires en résine. Parfaits pour les souvenirs, cadeaux promotionnels et la vente en gros de boutiques de cadeaux.", it: "Palle di neve, magneti da frigo e salvadanai in resina. Perfetti per souvenir, regali promozionali e ingrosso per negozi di regali." },

  "home.whyChoose.heading": { ar: "لماذا تختار كيليكولي كمصنّع تماثيل الراتنج الخاص بك", es: "Por Qué Elegir Kelikuli como su Fabricante de Figuras de Resina", pt: "Por Que Escolher a Kelikuli como Seu Fabricante de Figuras de Resina", ru: "Почему стоит выбрать Kelikuli в качестве производителя фигурок из смолы", fr: "Pourquoi Choisir Kelikuli comme Fabricant de Figurines en Résine", it: "Perché Scegliere Kelikuli come Produttore di Statuine in Resina" },
  "home.whyChoose.quality.title": { ar: "جودة منتج جيدة", es: "Buena Calidad del Producto", pt: "Boa Qualidade do Produto", ru: "Высокое качество продукции", fr: "Bonne Qualité de Produit", it: "Buona Qualità del Prodotto" },
  "home.whyChoose.quality.description": { ar: "نستخدم مواد فاخرة ومراقبة جودة صارمة لتقديم ألعاب راتنج متينة وآمنة وعالية الجودة تلبي المعايير العالمية.", es: "Utilizamos materiales premium y un control de calidad estricto para ofrecer juguetes de resina duraderos, seguros y de alta calidad que cumplen con los estándares globales.", pt: "Utilizamos materiais premium e controle de qualidade rigoroso para entregar brinquedos de resina duráveis, seguros e de alta qualidade que atendem aos padrões globais.", ru: "Мы используем качественные материалы и строгий контроль качества, чтобы предложить прочные, безопасные и высококачественные изделия из смолы, соответствующие мировым стандартам.", fr: "Nous utilisons des matériaux premium et un contrôle qualité strict pour livrer des jouets en résine durables, sûrs et de haute qualité, conformes aux normes internationales.", it: "Utilizziamo materiali premium e un rigoroso controllo qualità per offrire giocattoli in resina durevoli, sicuri e di alta qualità, conformi agli standard internazionali." },
  "home.whyChoose.custom.title": { ar: "خدمة التصنيع حسب الطلب", es: "Servicio a Medida", pt: "Serviço Sob Medida", ru: "Услуга индивидуального изготовления", fr: "Service Sur Mesure", it: "Servizio Su Misura" },
  "home.whyChoose.custom.description": { ar: "من الفكرة إلى المنتج النهائي، يقدم مصنع ألعاب الراتنج المخصص لدينا حلول OEM/ODM الكاملة — التصميم والقولبة والرسم اليدوي والتغليف بما يتناسب مع رؤية علامتك التجارية.", es: "Desde el concepto hasta el producto terminado, nuestra fábrica de juguetes de resina personalizados ofrece soluciones OEM/ODM completas — diseño, moldeado, pintura a mano y empaque acordes con la visión de su marca.", pt: "Do conceito ao produto final, nossa fábrica de brinquedos de resina personalizados oferece soluções OEM/ODM completas — design, moldagem, pintura à mão e embalagem alinhados à visão da sua marca.", ru: "От концепции до готового изделия — наш завод по производству изделий из смолы на заказ предлагает полный комплекс услуг OEM/ODM: дизайн, литьё, ручную роспись и упаковку в соответствии с видением вашего бренда.", fr: "Du concept au produit fini, notre usine de jouets en résine personnalisés propose des solutions OEM/ODM complètes — conception, moulage, peinture à la main et emballage adaptés à la vision de votre marque.", it: "Dal concept al prodotto finito, la nostra fabbrica di giocattoli in resina personalizzati offre soluzioni OEM/ODM complete — design, stampaggio, pittura a mano e packaging in linea con la visione del tuo brand." },
  "home.whyChoose.support.title": { ar: "دعم ما بعد البيع", es: "Soporte Postventa", pt: "Suporte Pós-Venda", ru: "Послепродажная поддержка", fr: "Support Après-Vente", it: "Assistenza Post-Vendita" },
  "home.whyChoose.support.description": { ar: "يقدم فريقنا المحترف استجابة سريعة وخدمة ما بعد بيع موثوقة، مما يضمن شراكات طويلة الأمد وراحة البال.", es: "Nuestro equipo profesional ofrece respuesta rápida y un servicio postventa confiable, garantizando asociaciones a largo plazo y tranquilidad.", pt: "Nossa equipe profissional oferece resposta rápida e um serviço pós-venda confiável, garantindo parcerias de longo prazo e tranquilidade.", ru: "Наша профессиональная команда обеспечивает быстрый отклик и надёжное послепродажное обслуживание, гарантируя долгосрочное партнёрство и спокойствие.", fr: "Notre équipe professionnelle offre une réponse rapide et un service après-vente fiable, garantissant des partenariats durables et une tranquillité d'esprit.", it: "Il nostro team professionale offre risposte rapide e un servizio post-vendita affidabile, garantendo partnership durature e serenità." },
  "home.whyChoose.reliable.title": { ar: "خبرة مصنع موثوقة", es: "Experiencia de Fábrica Confiable", pt: "Experiência de Fábrica Confiável", ru: "Надёжный опыт производства", fr: "Expérience d'Usine Fiable", it: "Esperienza di Fabbrica Affidabile" },
  "home.whyChoose.reliable.description": { ar: "تأسس في عام 2005، يجمع مصنع تماثيل البولي راتنج لدينا بين المعدات المتقدمة والحرفيين المهرة لضمان جودة ثابتة وتسليم في الوقت المحدد للطلبات بالجملة حول العالم.", es: "Establecida en 2005, nuestra fábrica de figuras de poliresina cuenta con equipos avanzados y artesanos calificados para garantizar calidad constante y entrega puntual en pedidos al por mayor en todo el mundo.", pt: "Fundada em 2005, nossa fábrica de figuras de poliresina conta com equipamentos avançados e artesãos qualificados para garantir qualidade consistente e entrega pontual em pedidos por atacado em todo o mundo.", ru: "Основанный в 2005 году, наш завод по производству полирезиновых фигурок использует современное оборудование и опытных мастеров, гарантируя стабильное качество и своевременную доставку оптовых заказов по всему миру.", fr: "Fondée en 2005, notre usine de figurines en polyrésine dispose d'équipements avancés et d'artisans qualifiés pour garantir une qualité constante et une livraison ponctuelle des commandes en gros dans le monde entier.", it: "Fondata nel 2005, la nostra fabbrica di statuine in poliresina dispone di attrezzature avanzate e artigiani qualificati per garantire qualità costante e consegne puntuali per ordini all'ingrosso in tutto il mondo." },

  "home.stats.founded": { ar: "تأسيس المصنع", es: "Fábrica Fundada", pt: "Fábrica Fundada", ru: "Год основания завода", fr: "Usine Fondée", it: "Fabbrica Fondata" },
  "home.stats.designs": { ar: "تصاميم المنتجات", es: "Diseños de Productos", pt: "Designs de Produtos", ru: "Дизайнов продукции", fr: "Designs de Produits", it: "Design di Prodotti" },
  "home.stats.employees": { ar: "موظفو الشركة", es: "Empleados de la Empresa", pt: "Funcionários da Empresa", ru: "Сотрудников компании", fr: "Employés de l'Entreprise", it: "Dipendenti dell'Azienda" },
  "home.stats.markets": { ar: "أسواق التصدير", es: "Mercados de Exportación", pt: "Mercados de Exportação", ru: "Экспортных рынков", fr: "Marchés d'Exportation", it: "Mercati di Esportazione" },

  "home.trustedBrands.heading": { ar: "موثوق به من قبل علامات تجارية عالمية", es: "Confiado por Marcas Globales", pt: "Confiado por Marcas Globais", ru: "Нам доверяют мировые бренды", fr: "Approuvé par des Marques Internationales", it: "Scelto da Brand Internazionali" },

  "home.oemProcess.eyebrow": { ar: "خدمة شاملة", es: "Servicio Integral", pt: "Serviço Completo", ru: "Услуги «под ключ»", fr: "Service Tout-en-Un", it: "Servizio Completo" },
  "home.oemProcess.heading": { ar: "خدمة ألعاب الراتنج الشاملة OEM/ODM", es: "Servicio Integral OEM/ODM de Juguetes de Resina", pt: "Serviço Completo OEM/ODM de Brinquedos de Resina", ru: "Комплексные услуги OEM/ODM по производству изделий из смолы", fr: "Service Tout-en-Un OEM/ODM de Jouets en Résine", it: "Servizio Completo OEM/ODM per Giocattoli in Resina" },
  "home.oemProcess.intro": { ar: "تقدم كيليكولي خدمات ألعاب الراتنج الشاملة OEM/ODM للعلامات التجارية وتجار الجملة وشركات الهدايا. من التصميم ثلاثي الأبعاد وصناعة القوالب وصب الراتنج والرسم اليدوي إلى الإنتاج بالجملة، نصنع تماثيل راتنج مخصصة وألعاب صناديق عشوائية وزينة وحرف قابلة للتحصيل.", es: "Kelikuli ofrece servicios integrales OEM/ODM de juguetes de resina para marcas, mayoristas y empresas de regalos. Desde diseño 3D, fabricación de moldes, moldeado de resina, pintura a mano hasta producción en masa, creamos figuras de resina personalizadas, juguetes blind box, adornos y artesanías coleccionables.", pt: "A Kelikuli oferece serviços completos OEM/ODM de brinquedos de resina para marcas, atacadistas e empresas de presentes. Do design 3D, fabricação de moldes, moldagem de resina, pintura à mão até a produção em massa, criamos figuras de resina personalizadas, brinquedos blind box, enfeites e artesanato colecionável.", ru: "Kelikuli предоставляет комплексные услуги OEM/ODM по производству изделий из смолы для брендов, оптовиков и подарочных компаний. От 3D-дизайна, изготовления форм, литья смолы и ручной росписи до массового производства — мы создаём фигурки на заказ, игрушки Blind Box, украшения и коллекционные изделия.", fr: "Kelikuli propose des services OEM/ODM tout-en-un de jouets en résine pour les marques, grossistes et entreprises de cadeaux. De la conception 3D, la fabrication de moules, le moulage de résine, la peinture à la main jusqu'à la production en masse, nous créons des figurines en résine personnalisées, des jouets blind box, des ornements et des objets de collection artisanaux.", it: "Kelikuli offre servizi completi OEM/ODM per giocattoli in resina destinati a brand, grossisti e aziende di gadget. Dalla progettazione 3D, creazione di stampi, colata della resina, pittura a mano fino alla produzione di massa, creiamo statuine in resina personalizzate, giocattoli blind box, ornamenti e manufatti da collezione." },
  "home.oemProcess.learnMore": { ar: "اعرف المزيد عن عمليتنا", es: "Más Información Sobre Nuestro Proceso", pt: "Saiba Mais Sobre Nosso Processo", ru: "Узнать больше о нашем процессе", fr: "En Savoir Plus Sur Notre Processus", it: "Scopri di Più sul Nostro Processo" },
  "home.oemProcess.qualityBadge": { ar: "الجودة في كل خطوة", es: "Calidad en Cada Paso", pt: "Qualidade em Cada Etapa", ru: "Качество на каждом этапе", fr: "Qualité à Chaque Étape", it: "Qualità in Ogni Fase" },
  "home.oemProcess.step1": { ar: "مراجعة الفكرة والتصميم الفني", es: "Revisión de Idea y Arte", pt: "Revisão de Ideia e Arte", ru: "Проработка идеи и дизайна", fr: "Revue de l'Idée et du Design", it: "Revisione dell'Idea e della Grafica" },
  "home.oemProcess.step2": { ar: "تصميم ثلاثي الأبعاد / نموذج أولي", es: "Diseño 3D / Prototipo", pt: "Design 3D / Protótipo", ru: "3D-дизайн / прототип", fr: "Design 3D / Prototype", it: "Design 3D / Prototipo" },
  "home.oemProcess.step3": { ar: "تطوير القوالب", es: "Desarrollo de Moldes", pt: "Desenvolvimento de Moldes", ru: "Разработка форм", fr: "Développement des Moules", it: "Sviluppo degli Stampi" },
  "home.oemProcess.step4": { ar: "صب الراتنج", es: "Moldeado de Resina", pt: "Moldagem de Resina", ru: "Литьё смолы", fr: "Moulage de Résine", it: "Colata della Resina" },
  "home.oemProcess.step5": { ar: "الرسم اليدوي", es: "Pintura a Mano", pt: "Pintura à Mão", ru: "Ручная роспись", fr: "Peinture à la Main", it: "Pittura a Mano" },
  "home.oemProcess.step6": { ar: "مراقبة الجودة والتغليف", es: "Control de Calidad y Empaque", pt: "Controle de Qualidade e Embalagem", ru: "Контроль качества и упаковка", fr: "Contrôle Qualité et Emballage", it: "Controllo Qualità e Imballaggio" },

  "home.service.heading": { ar: "مورد تماثيل الراتنج الخاص بك من الصين — خدمة OEM/ODM كاملة", es: "Su Proveedor de Figuras de Resina desde China — Servicio Completo OEM/ODM", pt: "Seu Fornecedor de Figuras de Resina da China — Serviço Completo OEM/ODM", ru: "Ваш поставщик фигурок из смолы из Китая — полный комплекс услуг OEM/ODM", fr: "Votre Fournisseur de Figurines en Résine depuis la Chine — Service Complet OEM/ODM", it: "Il Tuo Fornitore di Statuine in Resina dalla Cina — Servizio Completo OEM/ODM" },
  "home.service.intro": { ar: "بصفتنا مصنعًا لتماثيل التحصيل في تشجيانغ، الصين، تدعم كيليكولي الطلبات الشاملة من استشارة التصميم إلى الشحن العالمي. نحن متخصصون في تماثيل ديكور زاكا من الراتنج بالجملة، وتصنيع تماثيل راتنج موسمية OEM لعيد الميلاد وهالوين، وسلاسل الصناديق العشوائية المخصصة — نقبل طلبات عينات تماثيل الراتنج والجملة بكميات كبيرة.", es: "Como fábrica de figuras coleccionables en Zhejiang, China, Kelikuli respalda pedidos integrales desde la consulta de diseño hasta el envío global. Nos especializamos en figuras decorativas de resina Zakka al por mayor, OEM de figuras de resina de temporada para Navidad y Halloween, y series blind box personalizadas — aceptamos pedidos de muestra de figuras de resina y venta al por mayor.", pt: "Como fábrica de figuras colecionáveis em Zhejiang, China, a Kelikuli oferece suporte completo, da consultoria de design ao envio global. Somos especializados em figuras decorativas de resina Zakka no atacado, OEM de figuras de resina sazonais para Natal e Halloween, e séries blind box personalizadas — aceitamos pedidos de amostra de figuras de resina e atacado em grande volume.", ru: "Как завод коллекционных фигурок в провинции Чжэцзян, Китай, Kelikuli поддерживает заказы полного цикла — от консультации по дизайну до международной доставки. Мы специализируемся на оптовых декоративных фигурках из смолы в стиле Zakka, сезонных фигурках OEM для Рождества и Хэллоуина, а также индивидуальных сериях Blind Box — принимаем заказы на образцы и крупный опт.", fr: "En tant que fabricant de figurines de collection à Zhejiang, en Chine, Kelikuli accompagne les commandes de bout en bout, de la consultation design à l'expédition mondiale. Nous sommes spécialisés dans les figurines décoratives en résine Zakka en gros, les figurines saisonnières OEM pour Noël et Halloween, et les séries blind box personnalisées — nous acceptons les commandes d'échantillons et la vente en gros.", it: "In qualità di fabbrica di statuine da collezione a Zhejiang, in Cina, Kelikuli supporta ordini completi, dalla consulenza di design alla spedizione globale. Siamo specializzati in statuine decorative in resina Zakka all'ingrosso, statuine stagionali OEM per Natale e Halloween e serie blind box personalizzate — accettiamo ordini campione e ingrosso di grandi volumi." },
  "home.service.preSaleTitle": { ar: "خدمة ما قبل البيع", es: "Servicio Preventa", pt: "Serviço Pré-Venda", ru: "Предпродажное обслуживание", fr: "Service Avant-Vente", it: "Servizio Pre-Vendita" },
  "home.service.preSale1": { ar: "فهم احتياجات التصميم الخاصة بك والسوق المستهدف", es: "Comprender sus necesidades de diseño y mercado objetivo", pt: "Compreender suas necessidades de design e mercado-alvo", ru: "Изучение ваших требований к дизайну и целевого рынка", fr: "Comprendre vos besoins de conception et votre marché cible", it: "Comprendere le tue esigenze di design e il mercato di riferimento" },
  "home.service.preSale2": { ar: "تقديم عرض سعر احترافي وتحليل التكاليف", es: "Proporcionar cotización profesional y análisis de costos", pt: "Fornecer orçamento profissional e análise de custos", ru: "Профессиональный расчёт стоимости и анализ затрат", fr: "Fournir un devis professionnel et une analyse des coûts", it: "Fornire un preventivo professionale e un'analisi dei costi" },
  "home.service.preSale3": { ar: "تقديم حلول الحد الأدنى للطلب والإنتاج", es: "Ofrecer soluciones de MOQ y producción", pt: "Oferecer soluções de MOQ e produção", ru: "Решения по MOQ и производству", fr: "Proposer des solutions de MOQ et de production", it: "Offrire soluzioni di MOQ e produzione" },
  "home.service.preSale4": { ar: "تخطيط العينات وتأكيدها", es: "Planificación y confirmación de muestras", pt: "Planejamento e confirmação de amostras", ru: "Планирование и утверждение образцов", fr: "Planification et confirmation des échantillons", it: "Pianificazione e conferma dei campioni" },
  "home.service.productionTitle": { ar: "خدمة الإنتاج", es: "Servicio de Producción", pt: "Serviço de Produção", ru: "Услуги производства", fr: "Service de Production", it: "Servizio di Produzione" },
  "home.service.production1": { ar: "تأكيد العينات والموافقة على الإنتاج الضخم", es: "Confirmar muestras y aprobar la producción en masa", pt: "Confirmar amostras e aprovar a produção em massa", ru: "Утверждение образцов и одобрение массового производства", fr: "Confirmer les échantillons et approuver la production de masse", it: "Confermare i campioni e approvare la produzione di massa" },
  "home.service.production2": { ar: "تتبع سير الإنتاج وإبقاؤك على اطلاع", es: "Seguimiento del progreso de producción y mantenerlo informado", pt: "Acompanhamento do progresso da produção e manter você informado", ru: "Отслеживание хода производства и информирование вас", fr: "Suivi de la progression de la production et vous tenir informé", it: "Monitoraggio dell'avanzamento della produzione e aggiornamenti costanti" },
  "home.service.production3": { ar: "مراقبة جودة صارمة أثناء الإنتاج وقبل الشحن", es: "Control de calidad estricto durante la producción y antes del envío", pt: "Controle de qualidade rigoroso durante a produção e antes do envio", ru: "Строгий контроль качества в процессе производства и перед отгрузкой", fr: "Contrôle qualité strict pendant la production et avant l'expédition", it: "Controllo qualità rigoroso durante la produzione e prima della spedizione" },
  "home.service.production4": { ar: "تغليف احترافي وشحن في الوقت المحدد", es: "Empaque profesional y envío puntual", pt: "Embalagem profissional e envio pontual", ru: "Профессиональная упаковка и своевременная отгрузка", fr: "Emballage professionnel et expédition ponctuelle", it: "Imballaggio professionale e spedizione puntuale" },

  "home.recommended.heading": { ar: "منتجات موصى بها", es: "Productos Recomendados", pt: "Produtos Recomendados", ru: "Рекомендуемые товары", fr: "Produits Recommandés", it: "Prodotti Consigliati" },
  "home.recommended.viewAll": { ar: "عرض جميع مجموعات المنتجات", es: "Ver Todas las Colecciones de Productos", pt: "Ver Todas as Coleções de Produtos", ru: "Смотреть все коллекции товаров", fr: "Voir Toutes les Collections de Produits", it: "Vedi Tutte le Collezioni di Prodotti" },

  "home.latestProducts.eyebrow": { ar: "وصل حديثًا", es: "Novedades", pt: "Novidades", ru: "Новинки", fr: "Nouveautés", it: "Novità" },
  "home.latestProducts.heading": { ar: "أحدث المنتجات", es: "Últimos Productos", pt: "Últimos Produtos", ru: "Последние товары", fr: "Derniers Produits", it: "Ultimi Prodotti" },
  "home.latestProducts.viewAll": { ar: "عرض الكل", es: "Ver Todo", pt: "Ver Tudo", ru: "Смотреть все", fr: "Voir Tout", it: "Vedi Tutto" },
  "home.latestProducts.viewAllMobile": { ar: "عرض جميع المنتجات", es: "Ver Todos los Productos", pt: "Ver Todos os Produtos", ru: "Смотреть все товары", fr: "Voir Tous les Produits", it: "Vedi Tutti i Prodotti" },

  "home.customBanner.heading": { ar: "مصنع OEM لألعاب الراتنج المخصصة — رؤيتك، حرفيتنا", es: "Fábrica OEM de Juguetes de Resina Personalizados — Su Visión, Nuestro Arte", pt: "Fábrica OEM de Brinquedos de Resina Personalizados — Sua Visão, Nossa Arte", ru: "Завод OEM по производству изделий из смолы на заказ — ваше видение, наше мастерство", fr: "Usine OEM de Jouets en Résine Personnalisés — Votre Vision, Notre Savoir-Faire", it: "Fabbrica OEM di Giocattoli in Resina Personalizzati — La Tua Visione, la Nostra Arte" },
  "home.customBanner.paragraph1": { ar: "بصفتنا موردًا موثوقًا لتماثيل الراتنج من الصين، نساعد العلامات التجارية وتجار الجملة والاستوديوهات الإبداعية على تحويل الأفكار الأصلية إلى تماثيل راتنج عالية الجودة ومقتنيات صناديق عشوائية وديكور زاكا — من الفكرة إلى المنتج النهائي.", es: "Como proveedor confiable de figuras de resina desde China, ayudamos a marcas, mayoristas y estudios creativos a convertir ideas originales en figuras de resina de alta calidad, coleccionables blind box y decoración Zakka — del concepto al producto terminado.", pt: "Como fornecedor confiável de figuras de resina da China, ajudamos marcas, atacadistas e estúdios criativos a transformar ideias originais em figuras de resina de alta qualidade, colecionáveis blind box e decoração Zakka — do conceito ao produto final.", ru: "Как надёжный поставщик фигурок из смолы из Китая, мы помогаем брендам, оптовикам и творческим студиям воплощать оригинальные идеи в высококачественные фигурки из смолы, коллекционные Blind Box и декор Zakka — от концепции до готового изделия.", fr: "En tant que fournisseur fiable de figurines en résine depuis la Chine, nous aidons les marques, grossistes et studios créatifs à transformer des idées originales en figurines en résine de haute qualité, objets de collection blind box et décoration Zakka — du concept au produit fini.", it: "In qualità di fornitore affidabile di statuine in resina dalla Cina, aiutiamo brand, grossisti e studi creativi a trasformare idee originali in statuine in resina di alta qualità, oggetti da collezione blind box e decorazioni Zakka — dal concept al prodotto finito." },
  "home.customBanner.paragraph2": { ar: "كيليكولي هي شركة تصنيع ألعاب راتنج مخصصة بحد أدنى منخفض للطلب — تدعم طلبات العينات والدفعات الصغيرة وتماثيل الراتنج بالجملة بكميات كبيرة. كل قطعة مرسومة يدويًا بواسطة حرفيين مهرة، مما يجعلنا الخيار الأمثل لتصنيع ألعاب الراتنج OEM للعلامات التجارية التي تبحث عن الجودة والمرونة.", es: "Kelikuli es un fabricante de juguetes de resina personalizados con MOQ bajo — apoyamos pedidos de muestra, lotes pequeños y figuras de resina al por mayor de gran volumen. Cada pieza está pintada a mano por artesanos calificados, lo que nos convierte en el fabricante OEM de juguetes de resina preferido para marcas que buscan calidad y flexibilidad.", pt: "A Kelikuli é uma fabricante de brinquedos de resina personalizados com MOQ baixo — apoiamos pedidos de amostra, lotes pequenos e figuras de resina no atacado em grande volume. Cada peça é pintada à mão por artesãos qualificados, o que nos torna a fabricante OEM de brinquedos de resina preferida por marcas que buscam qualidade e flexibilidade.", ru: "Kelikuli — производитель изделий из смолы на заказ с низким MOQ: мы поддерживаем заказы образцов, небольшие партии и крупный опт фигурок из смолы. Каждое изделие расписывается вручную опытными мастерами, что делает нас предпочтительным OEM-производителем изделий из смолы для брендов, ценящих качество и гибкость.", fr: "Kelikuli est un fabricant de jouets en résine personnalisés avec un MOQ faible — nous prenons en charge les commandes d'échantillons, les petites séries et les figurines en résine en gros volume. Chaque pièce est peinte à la main par des artisans qualifiés, ce qui fait de nous le fabricant OEM de jouets en résine de référence pour les marques recherchant qualité et flexibilité.", it: "Kelikuli è un produttore di giocattoli in resina personalizzati con MOQ basso — supportiamo ordini campione, piccoli lotti e statuine in resina all'ingrosso di grandi volumi. Ogni pezzo è dipinto a mano da artigiani esperti, il che ci rende il produttore OEM di giocattoli in resina di riferimento per i brand che cercano qualità e flessibilità." },
  "home.customBanner.cta": { ar: "احصل على عرض سعر مجاني", es: "Obtener Cotización Gratis", pt: "Obter Orçamento Gratuito", ru: "Получить бесплатное предложение", fr: "Obtenir un Devis Gratuit", it: "Richiedi un Preventivo Gratuito" },
  "home.customBanner.highlight.design": { ar: "تصميم إبداعي", es: "Diseño Creativo", pt: "Design Criativo", ru: "Креативный дизайн", fr: "Design Créatif", it: "Design Creativo" },
  "home.customBanner.highlight.quality": { ar: "جودة فائقة", es: "Calidad Premium", pt: "Qualidade Premium", ru: "Премиальное качество", fr: "Qualité Premium", it: "Qualità Premium" },
  "home.customBanner.highlight.global": { ar: "معايير عالمية", es: "Estándares Globales", pt: "Padrões Globais", ru: "Мировые стандарты", fr: "Normes Internationales", it: "Standard Internazionali" },
  "home.customBanner.highlight.delivery": { ar: "تسليم موثوق", es: "Entrega Confiable", pt: "Entrega Confiável", ru: "Надёжная доставка", fr: "Livraison Fiable", it: "Consegna Affidabile" },

  "home.featureBadges.design.title": { ar: "تصميم أصلي", es: "Diseño Original", pt: "Design Original", ru: "Оригинальный дизайн", fr: "Design Original", it: "Design Originale" },
  "home.featureBadges.design.description": { ar: "حوّل أفكارك إلى ألعاب راتنج فريدة وتماثيل قابلة للتحصيل.", es: "Convierta sus ideas en juguetes de resina únicos y figuras coleccionables.", pt: "Transforme suas ideias em brinquedos de resina únicos e figuras colecionáveis.", ru: "Превратим ваши идеи в уникальные игрушки из смолы и коллекционные фигурки.", fr: "Transformez vos idées en jouets en résine uniques et figurines de collection.", it: "Trasforma le tue idee in giocattoli in resina unici e statuine da collezione." },
  "home.featureBadges.quality.title": { ar: "ضمان الجودة", es: "Garantía de Calidad", pt: "Garantia de Qualidade", ru: "Гарантия качества", fr: "Assurance Qualité", it: "Garanzia di Qualità" },
  "home.featureBadges.quality.description": { ar: "مراقبة جودة صارمة لمنتجات الراتنج المرسومة يدويًا.", es: "Control de calidad estricto para productos de resina pintados a mano.", pt: "Controle de qualidade rigoroso para produtos de resina pintados à mão.", ru: "Строгий контроль качества изделий из смолы ручной росписи.", fr: "Contrôle qualité strict pour les produits en résine peints à la main.", it: "Controllo qualità rigoroso per i prodotti in resina dipinti a mano." },
  "home.featureBadges.oem.title": { ar: "خدمة OEM وODM", es: "Servicio OEM y ODM", pt: "Serviço OEM e ODM", ru: "Услуги OEM и ODM", fr: "Service OEM et ODM", it: "Servizio OEM e ODM" },
  "home.featureBadges.oem.description": { ar: "تصميم مخصص وتطوير قوالب ورسم وتغليف.", es: "Diseño personalizado, desarrollo de moldes, pintura y empaque.", pt: "Design personalizado, desenvolvimento de moldes, pintura e embalagem.", ru: "Индивидуальный дизайн, разработка форм, роспись и упаковка.", fr: "Design personnalisé, développement de moules, peinture et emballage.", it: "Design personalizzato, sviluppo stampi, pittura e imballaggio." },
  "home.featureBadges.global.title": { ar: "شريك عالمي", es: "Socio Global", pt: "Parceiro Global", ru: "Глобальный партнёр", fr: "Partenaire International", it: "Partner Globale" },
  "home.featureBadges.global.description": { ar: "موثوق به من قبل العلامات التجارية والمستوردين وتجار الجملة حول العالم.", es: "Confiado por marcas, importadores y mayoristas de todo el mundo.", pt: "Confiado por marcas, importadores e atacadistas em todo o mundo.", ru: "Нам доверяют бренды, импортёры и оптовики по всему миру.", fr: "Approuvé par des marques, importateurs et grossistes du monde entier.", it: "Scelto da brand, importatori e grossisti di tutto il mondo." },
};

async function main() {
  console.log("Upserting languages...");
  for (const lang of LANGUAGES) {
    await prisma.language.upsert({
      where: { code: lang.code },
      update: { name: lang.name, nativeName: lang.nativeName, flag: lang.flag, active: true },
      create: { code: lang.code, name: lang.name, nativeName: lang.nativeName, flag: lang.flag, active: true, sortOrder: lang.sortOrder },
    });
  }

  console.log("Upserting translations...");
  let count = 0;
  for (const [key, values] of Object.entries(T)) {
    for (const lang of LANGUAGES) {
      const value = values[lang.code];
      if (!value) continue;
      await prisma.translation.upsert({
        where: { key_languageCode: { key, languageCode: lang.code } },
        update: { value },
        create: { key, languageCode: lang.code, value },
      });
      count++;
    }
  }
  console.log(`Done. ${Object.keys(T).length} keys x ${LANGUAGES.length} languages = ${count} translation rows upserted.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
